name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - master


# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
    # download aad repository
    - uses: actions/checkout@v2
    # Install aad conda environment
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: aad-book
        environment-file: book/environment.yml
        python-version: 3.7
        auto-activate-base: false
    # Build the book
    - name: Build the book
      run: |
        jupyter-book build book/
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: book/_build/html